wordpress:
      depends on:
       - db 
      image: wordpress:latest
      ports:
       - "8000:80"
      restart: always
      environment:
       - WORDPRESS_DB_HOST=db:3306
       - WORDPRESS_DB_USER=wordpress
       - WORDPRESS_DB_PASSWORD=wordpress
       - WORDPRESS_DB_NAME=wordpress 